// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User 用户表
type User struct {
	ID           int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                        // ID
	UserAccount  string         `gorm:"column:user_account;not null;comment:账户" json:"user_account"`                         // 账户
	UserPassword string         `gorm:"column:user_password;not null;comment:用户密码" json:"user_password"`                     // 用户密码
	UserName     string         `gorm:"column:user_name;not null;comment:用户名" json:"user_name"`                              // 用户名
	UserRole     string         `gorm:"column:user_role;not null;comment:权限角色: admin/user" json:"user_role"`                 // 权限角色: admin/user
	LastLoginAt  *string        `gorm:"column:last_login_at;comment:最后登陆时间" json:"last_login_at"`                            // 最后登陆时间
	CreatedAt    time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt    time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间（软删除标记）" json:"deleted_at"`                             // 删除时间（软删除标记）
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
