app:
  host: 127.0.0.1
  port: :8123
database:
  mysql:
    host: 127.0.0.1
    port: 3306
    user: root
    password: 12345678
    dbname: honey_db
  redis:
    addr: 127.0.0.1:6379
    pwd: 12345678
    db: 0
jwt:
  exp:
  signal:
session:
  sessionCookieKey: session_id
  sessionRedisPrefix: "session:"
  sessionExpire: 24   # Hour